### PR TITLE
Remove :FINAL patches

### PR DESCRIPTION
**Pull request by blowfishpro**
No patches in a distributed mod should be :FINAL, this prevents any
other patches from being run after them, and the :FINAL pass is usually
reserved for personal patches that won't be distributed

### CODE REVIEW

**Comment by Raptor831** [comment]
Agreed. Thank you.

**Comment by blowfishpro** [comment]
Oh, would it be possible to release this relatively soon?  I added a patch to RF to get rid of the stock resources, but it turns out that RF Stockalike's life support patches depend on MonoPropellant still being there.  With these changes, everything applies in the correct order so it's not an issue.

**Comment by Raptor831** [comment]
Ask and ye shall receive. ;-)

**Comment by blowfishpro** [comment]
Thank you!

**Pull request merged**
