### PR TITLE
Updated configs for NFSpacecraft engines

### LINKED ISSUE #85: Fix NFSpacecraft configs
Hey @Raptor831 ,

Not sure if you're aware of this issue or not, but the engines implemented by NFSpacecraft [LV-T95, LV-T95-8, and LV-T18] were deprecated back in v0.6.1.  The new engines, therefore, do not have RL fuel mixtures; they just run on Monopropellant now.

I'm not very knowledgeable about real engine configs; however, I will try my best (and probably submit a PR later). If I make a fool of myself in making real configs for those engines, please point that out to me.

Thanks in advance.

### PR DESCRIPTION
**Pull request by TotallyNotHuman**
Fixes #85 .

As mentioned in commit e635b37, the LV-95-6 and LV-601-4 have integrated fuel tanks that can be toggled using B9PartSwitch. I'm not really sure if they can be patched to have MFT-type tanks, as the (stock) engine configs reveal that the tanks are type Monopropellant.

Please also check the engine configs before merging, as I am not a rocketry aficionado. Completely unrealistic configs may abound.

### CODE REVIEW

**Comment by TotallyNotHuman** [comment]
Is the CI build supposed to fail like that? As I see it, it's not my code, but because of the lack of a Rakefile...?

Warning: Hell of a long stacktrace below. Navigate at own caution.

```
Worker information
hostname: i-05f9a44-precise-production-2-worker-org-docker.travisci.net:484cb29f-f728-47f3-bd4b-1486c9d2c523
version: v2.5.0 https://github.com/travis-ci/worker/tree/da3a43228dffc0fcca5a46569ca786b22991979f
instance: 7d92ba7:travis:ruby
startup: 635.03408ms
Could not find .travis.yml, using standard configuration.
Build system information
Build language: ruby
Build group: stable
Build dist: precise
Build id: 215127943
Job id: 215127944
travis-build version: d39932a43
Build image provisioning date and time
Thu Feb  5 15:09:33 UTC 2015
Operating System Details
Distributor ID:	Ubuntu
Description:	Ubuntu 12.04.5 LTS
Release:	12.04
Codename:	precise
Linux Version
3.13.0-29-generic
Cookbooks Version
a68419e https://github.com/travis-ci/travis-cookbooks/tree/a68419e
GCC version
gcc (Ubuntu/Linaro 4.6.3-1ubuntu5) 4.6.3
Copyright (C) 2011 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

LLVM version
clang version 3.4 (tags/RELEASE_34/final)
Target: x86_64-unknown-linux-gnu
Thread model: posix
Pre-installed Ruby versions
ruby-1.9.3-p551
Pre-installed Node.js versions
v0.10.36
Pre-installed Go versions
1.4.1
Redis version
redis-server 2.8.19
riak version
2.0.2
MongoDB version
MongoDB 2.4.12
CouchDB version
couchdb 1.6.1
Neo4j version
1.9.4
RabbitMQ Version
3.4.3
ElasticSearch version
1.4.0
Installed Sphinx versions
2.0.10
2.1.9
2.2.6
Default Sphinx version
2.2.6
Installed Firefox version
firefox 31.0esr
PhantomJS version
1.9.8
ant -version
Apache Ant(TM) version 1.8.2 compiled on December 3 2011
mvn -version
Apache Maven 3.2.5 (12a6b3acb947671f09b81f49094c53f426d8cea1; 2014-12-14T17:29:23+00:00)
Maven home: /usr/local/maven
Java version: 1.7.0_76, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-7-oracle/jre
Default locale: en_US, platform encoding: ANSI_X3.4-1968
OS name: "linux", version: "3.13.0-29-generic", arch: "amd64", family: "unix"

$ export DEBIAN_FRONTEND=noninteractive
Reading package lists...
Building dependency tree...
Reading state information...
The following extra packages will be installed:
  libc-bin libc-dev-bin libc6-dev
Suggested packages:
  glibc-doc
The following packages will be upgraded:
  libc-bin libc-dev-bin libc6 libc6-dev
4 upgraded, 0 newly installed, 0 to remove and 271 not upgraded.
Need to get 8,856 kB of archives.
After this operation, 13.3 kB of additional disk space will be used.
Get:1 http://us.archive.ubuntu.com/ubuntu/ precise-updates/main libc6-dev amd64 2.15-0ubuntu10.18 [2,948 kB]
Get:2 http://us.archive.ubuntu.com/ubuntu/ precise-updates/main libc-dev-bin amd64 2.15-0ubuntu10.18 [84.5 kB]
Get:3 http://us.archive.ubuntu.com/ubuntu/ precise-updates/main libc-bin amd64 2.15-0ubuntu10.18 [1,178 kB]
Get:4 http://us.archive.ubuntu.com/ubuntu/ precise-updates/main libc6 amd64 2.15-0ubuntu10.18 [4,646 kB]
Fetched 8,856 kB in 0s (34.6 MB/s)
Preconfiguring packages ...
(Reading database ... 71420 files and directories currently installed.)
Preparing to replace libc6-dev 2.15-0ubuntu10.10 (using .../libc6-dev_2.15-0ubuntu10.18_amd64.deb) ...
Unpacking replacement libc6-dev ...
Preparing to replace libc-dev-bin 2.15-0ubuntu10.10 (using .../libc-dev-bin_2.15-0ubuntu10.18_amd64.deb) ...
Unpacking replacement libc-dev-bin ...
Preparing to replace libc-bin 2.15-0ubuntu10.10 (using .../libc-bin_2.15-0ubuntu10.18_amd64.deb) ...
Unpacking replacement libc-bin ...
Processing triggers for man-db ...
Setting up libc-bin (2.15-0ubuntu10.18) ...
(Reading database ... 71419 files and directories currently installed.)
Preparing to replace libc6 2.15-0ubuntu10.10 (using .../libc6_2.15-0ubuntu10.18_amd64.deb) ...
Unpacking replacement libc6 ...
Setting up libc6 (2.15-0ubuntu10.18) ...
Setting up libc-dev-bin (2.15-0ubuntu10.18) ...
Setting up libc6-dev (2.15-0ubuntu10.18) ...
Processing triggers for libc-bin ...
ldconfig deferred processing now taking place
$ git clone --depth=50 https://github.com/Raptor831/RFStockalike.git Raptor831/RFStockalike
Cloning into 'Raptor831/RFStockalike'...
remote: Counting objects: 604, done.
remote: Compressing objects: 100% (199/199), done.
remote: Total 604 (delta 413), reused 579 (delta 399), pack-reused 0
Receiving objects: 100% (604/604), 979.38 KiB | 0 bytes/s, done.
Resolving deltas: 100% (413/413), done.
Checking connectivity... done.

$ cd Raptor831/RFStockalike
$ git fetch origin +refs/pull/86/merge:
remote: Counting objects: 26, done.
remote: Compressing objects: 100% (14/14), done.
remote: Total 26 (delta 21), reused 16 (delta 12), pack-reused 0
Unpacking objects: 100% (26/26), done.
From https://github.com/Raptor831/RFStockalike
 * branch            refs/pull/86/merge -> FETCH_HEAD

$ git checkout -qf FETCH_HEAD

This job is running on container-based infrastructure, which does not allow use of 'sudo', setuid and setguid executables.
If you require sudo, add 'sudo: required' to your .travis.yml
See https://docs.travis-ci.com/user/workers/container-based-infrastructure/ for details.
$ rvm use default
Using /home/travis/.rvm/gems/ruby-1.9.3-p551

$ ruby --version
ruby 1.9.3p551 (2014-11-13 revision 48407) [x86_64-linux]
$ rvm --version
rvm 1.26.10 (latest-minor) by Wayne E. Seguin <wayneeseguin@gmail.com>, Michal Papis <mpapis@gmail.com> [https://rvm.io/]
$ bundle --version
Bundler version 1.7.6
$ gem --version
2.4.5
$ rake
rake aborted!
No Rakefile found (looking for: rakefile, Rakefile, rakefile.rb, Rakefile.rb)
/home/travis/.rvm/gems/ruby-1.9.3-p551/bin/ruby_executable_hooks:15:in `eval'
/home/travis/.rvm/gems/ruby-1.9.3-p551/bin/ruby_executable_hooks:15:in `<main>'
(See full trace by running task with --trace)

The command "rake" exited with 1.

Done. Your build exited with 1.
```

**Comment by Raptor831** [comment]
The CI "build" doesn't do anything at the moment, so no worries. I think I was setting up some CI at some point and never finished.

**Comment by TotallyNotHuman** [comment]
Ah, thanks for the clearup.

Regarding those configs: are they realistic enough or do you think that they need more tweaking? Bear in mind that I used those engines' original masses and thrust values (i.e. from the NFSpacecraft cfgs) and so they might not be 100% realistic.

**Comment by jbwagner** [comment]
I didn't run the math on the TWR, but if you kept the "stock" masses they'll be too heavy. When you use the generator (which it appears you did), you'll see green on the TWR when you get the right mass, indicating that the TWR is in the right range. Honestly, even yellow on that alert is fine, but stock mass will be too much by like a factor of 5 or so.

**Comment by TotallyNotHuman** [comment]
@jbwagner

I kept the 'stock' mass, but messed around with the ISP multiplier until TWR was in the green. Would that have the same effect as modifying the mass, or would I have to rekerjigger the mass?

**Comment by jbwagner** [comment]
Mass would be better. RF is used (in part) to bring masses of tanks and engines in-line with realistic measures. Altering Isp would probably "work", but it's not really the better way to go. The masses will feel *really* small compared to KSP's usual, but that's ok!

**Comment by TotallyNotHuman** [comment]
Gotcha. It's late where I am, so I'll probably whip up a new config (with real masses) in the morn. Expect a PR sometime tomorrow.

**Pull request merged**
