### PR TITLE
StockRevamp Mk1-2 RCS and RLA Cutter revision

### PR DESCRIPTION
**Pull request by lurkoholic**
Added multiple propellants for the Mk1-2 RCS system.

For the RLA "Cutter", I changed the tech level to Advanced Rocketry and the Isp multipliers to 1.0 (webapp). This gave a mass of ~0.52. Feel free to up the Isp multipliers and mass to match.

### CODE REVIEW

**Comment by ImAHungryMan** [comment]
Hello again.

I've taken a second look at the aerospike. Turns out that the current version of RLA has since upgraded the aerospike so the old values should no longer apply. Therefore, I think the ISPs should stay at around 365/360. 

A mass of 1.5t is indeed too much though. I suggest a mass of about 0.47t. This will give it a TWR of around 45 which was apparently the goal TWR for an aerospike design.

**Comment by lurkoholic** [comment]
I'm not sure if a sea level ISP of 360s is realistic? I'm also not an expert :). 

Your TWR sounds pretty good. Here's a study for a truncated linear aerospike (hydrolox): http://enu.kz/repository/2010/AIAA-2010-7060.pdf

Their lightweight version had 460/387 ISP with TWR of 51 (the heavier version was ~35), so I would guess a kerolox version would be higher. Maybe TL8 weight savings could be adjusted for aerospikes?

If I get a chance I'll look at this again tonight.

**Comment by ImAHungryMan** [comment]
I don't think it's very realistic either. Also not an expert :) 

However, Raptor831 likes to keep engines as close to the original mod author's intentions as possible while still lending them a semblance of realism. So the usual process is to use the original part's values as much as possible and then adjust mass to compensate.

And yeah that's actually the article I used to get the "around 45 TWR" figure. If you want, you can create a new engine off the RLA cutter with values taken from that article. I also recommend taking a look at the Realism Overhaul repo.

**Comment by lurkoholic** [comment]
That engine's "niche" is high SL ISP, so the increased mass is probably more than offset by the increased SL thrust. A little extra mass on a first stage isn't a very big deal. 

I'll close this pull request and resubmit the other file by itself. If I make any more tweaks to the Cutter, I'll make it closer to your specs. Thanks for the feedback!

**Pull request closed without merging**
