### PR TITLE
Assigning ignitions according to engine type

### PR DESCRIPTION
**Pull request by ImAHungryMan**
Also:

- updated Space-Y with new thrust scaling and SRB thrust curves
- added missing Space-Y SRBs
- added RLA aerospike

I tried to update the check in Stockaliike_Tantares.cfg to prevent conflicts but it didn't work :/ Pointers please?

### CODE REVIEW

**Comment by Raptor831** [comment]
The check should be (not) whatever the :FOR[] is called in the Tantares file. I'm wondering if we even need the file if the RF configs come with the mod itself...

**Comment by ImAHungryMan** [comment]
I'd prefer deprecating it. The ones with Tantares are more up-to-date. And
kept that way by Niemand303 who evidently knows a lot about this stuff.

**Comment by ImAHungryMan** [comment]
Oh and two questions:

"ignitionsAvailable = 0" means infinite, right?

And should NTRs have to wait for their fuel to settle before igniting? I'm not an expert but that doesn't seem right.

**Comment by Raptor831** [comment]
Ok, we can just depreciate it. Neimand303 was on top of things with Tantares, so no worries there.

For ignitions, 0 means unlimited.

NTRs still have to pump the fuel from the tanks to the engine somehow. Unless it's pressure fed (i.e. ServiceModule tanks) it's still gotta be at the right end of the rocket. :-) I'd leave it. Not really an expert either, but that'd be my thought.

**Comment by ImAHungryMan** [comment]
Cool. And sure sounds about right. Didn't find anything definitive on the
Engine Ignitor thread. And now that I think about, there's probably no one
alive who is an expert :)

**Comment by lurkoholic** [comment]
ImAHungryMan,  Why is the RLA Cutter 1.5 tons? Isn't that too heavy? The previous version was 0.39 tons, and the ISP was 350s/315s. Thanks for adding the Methalox mode :).

**Comment by ImAHungryMan** [comment]
Huh. Not sure what I was thinking there. Feel free to change it. I won't be
in a position to do so for the next few days. Nice catch.

**Pull request merged**
