### PR TITLE
More engines and small fixes

### PR DESCRIPTION
**Pull request by ImAHungryMan**
- Updated StarShine Industries (in case you didn't get it by web-app)
- Support for BobCat's Soviet engines
- Support for BoxSat
- Added missing LEM Ascent engine for FASA
- Corrected fuel for Critter Crawler from BahamutoD
- Support for Chaka Monkey
- Added AJE check in B9_modularEngines.cfg
- Removed B9 VS1 VTOL engine from Stockalike_B9.cfg because it's a jet engine

Let me know if you have a problem with any of this.

### CODE REVIEW

**Comment by Raptor831** [comment]
Of note: there are two VTOL engines in B9. One was an LF/O engine, and one was a jet engine. I don't have the names in front of me, but I believe this one was the LF/O version.

**Comment by ImAHungryMan** [comment]
Ha. So it seems. I'll add it back in a bit.

**Comment by Raptor831** [comment]
Cool.

Also, thanks a ton for doing Chaka Monkey! If I had more RAM to spare, that'd be one mod I'd be using. Was planning on getting to that eventually.

**Comment by ImAHungryMan** [comment]
I can send you my personal Chaka Monkey "Lite" version if you think that might help.

And about the B9 VTOL, should it not have more ignitions? It currently only has one and VTOL engines would probably need to be restarted a lot.

**Comment by Raptor831** [comment]
You are correct. I'd go ahead and give it at least 24, if not just make it 0 (which is unlimited).

**Comment by ImAHungryMan** [comment]
Whoops! I didn't mean to push those last two commits yet. But since they're there I might as well bring them up for discussion.

Ahem. I request that the AJE check for the jet engines catch-all be removed because AJE does not yet have configs for every jet engine available. I don't think the catch-all should be nullified just because AJE is installed.

Is this reasonable?

**Comment by Raptor831** [comment]
Yeah, the AJE check removal is reasonable.

**Comment by ImAHungryMan** [comment]
Great thanks. 

Just added a missing Bobcat engine and all the new engines from the KOSMOS 0.90 release by the way.

**Comment by Raptor831** [comment]
Awesome. Gonna accept this now, as it's long overdue. :-)

**Pull request merged**
